export type StoreErrorCode =
  | "database_closed"
  | "schema_unavailable"
  | "schema_invalid"
  | "vault_parent_missing"
  | "vault_identity_mismatch"
  | "schema_version_mismatch"
  | "volatile_store_rejected"
  | "durability_unavailable"
  | "capture_not_prepared"
  | "scope_not_allowed"
  | "scope_not_registered"
  | "scope_conflict"
  | "session_not_registered"
  | "capture_conflict"
  | "capture_paused"
  | "capture_rejected"
  | "capture_invariant"
  | "capture_write_failed"
  | "native_observation_conflict"
  | "native_observation_blocked"
  | "native_scan_invalid"
  | "native_cursor_conflict"
  | "scope_write_failed"
  | "session_write_failed"
  | "schema_migration_failed"
  | "backup_invalid"
  | "backup_target_exists"
  | "backup_busy"
  | "backup_aborted"
  | "restore_invalid"
  | "restore_busy"
  | "restore_authority_mismatch"
  | "restore_quarantined"
  | "restore_aborted"
  | "restore_target_exists"
  | "auth_invalid"
  | "auth_write_failed"
  | "policy_invalid"
  | "output_not_allowed"
  | "purge_scope_not_allowed"
  | "purge_epoch_mismatch"
  | "purge_selection_invalid"
  | "purge_operation_conflict"
  | "purge_pending"
  | "query_trace_conflict"
  | "query_trace_write_failed"
  | "revision_invalid"
  | "revision_conflict"
  | "revision_write_failed"
  | "job_invalid"
  | "job_not_found"
  | "job_claim_conflict"
  | "job_lease_expired"
  | "job_stale"
  | "job_write_failed"
  | "attempt_invalid"
  | "attempt_not_found"
  | "attempt_conflict"
  | "attempt_lease_expired"
  | "attempt_stale"
  | "attempt_budget_paused"
  | "attempt_deadline"
  | "attempt_cleanup_pending"
  | "attempt_write_failed"
  | "transfer_invalid"
  | "transfer_target_exists"
  | "transfer_conflict"
  | "transfer_blocked"
  | "transfer_write_failed"
  | "read_failed";

export class StoreError extends Error {
  readonly code: StoreErrorCode;

  constructor(code: StoreErrorCode, cause?: unknown) {
    super(code, cause instanceof Error ? { cause } : undefined);
    this.name = "StoreError";
    this.code = code;
  }
}
